### PR TITLE
Add makefile and update Readme file

### PR DESCRIPTION
**Pull request by rojasTob**

### CODE REVIEW

**Review by bharatmurali — CHANGES_REQUESTED** [review]
```Traceback (most recent call last):
  File "./manage.py", line 17, in <module>
    raise ImportError(
ImportError: Couldn't import Django. Are you sure it's installed and available on your PYTHONPATH environment variable? Did you forget to activate a virtual environment?```

getting this^ when using Docker.

**Comment by rojasTob** [comment]
Hey @bharatmurali. I've been reviewing this one, but it is still not working for Macos :( . For now, I've removed the make commands in the Dockerfile in order to avoid the virtualenv issue.  Let me know your feedback. Thanks!  cc/ @po5i

**Review by po5i — COMMENTED** [review]
Looks good to me. I tested on my local and I was able to reproduce the Docker issue. This is really weird. I think we can go without the Makefile for now.

Please add the macos-latest and windows-latest to the CI.

**Review by bharatmurali — APPROVED** [review]
looks good!

**Pull request merged**
